"use strict";

/**
 * Integration catalogue — static definitions of every supported provider.
 *
 * availabilityStatus:
 *   "available"    — backend adapter is implemented and can be connected now
 *   "beta"         — limited or partial implementation; opt-in only
 *   "coming_soon"  — not yet implemented; UI shows a request button only
 */

const CATEGORIES = {
  MONITORING:  "monitoring_alerting",
  TELEMETRY:   "telemetry_observability",
  CLOUD:       "cloud",
  INFRA:       "infrastructure",
  INCIDENT:    "incident_management",
  COMMS:       "communication",
  DATA:        "databases_queues",
  DEV:         "developer_tools",
  CUSTOM:      "custom",
};

/** @type {IntegrationDefinition[]} */
const CATALOGUE = [
  // ── Available ─────────────────────────────────────────────────────────────
  {
    provider:          "webhook_incoming",
    displayName:       "Generic Incoming Webhook",
    category:          CATEGORIES.CUSTOM,
    description:       "Receive events from any external system via a signed HTTP POST webhook. AIRA generates a unique URL and validates HMAC-SHA256 signatures.",
    capabilities:      ["receive_events", "normalize_events"],
    availabilityStatus: "available",
    documentationUrl:  null,
    icon:              "webhook",
    configSchemaVersion: 1,
  },
  {
    provider:          "webhook_outgoing",
    displayName:       "Generic Outgoing Webhook",
    category:          CATEGORIES.CUSTOM,
    description:       "Push incident and monitor events to any HTTP endpoint. Supports custom headers, payload templates, and retry logic.",
    capabilities:      ["send_notifications"],
    availabilityStatus: "available",
    documentationUrl:  null,
    icon:              "webhook",
    configSchemaVersion: 1,
  },
  {
    provider:          "prometheus_alertmanager",
    displayName:       "Prometheus Alertmanager",
    category:          CATEGORIES.MONITORING,
    description:       "Receive firing and resolved alerts from Prometheus Alertmanager via the webhook receiver. Maps alert labels to AIRA incidents.",
    capabilities:      ["receive_events", "normalize_events"],
    availabilityStatus: "available",
    documentationUrl:  "https://prometheus.io/docs/alerting/latest/alertmanager/",
    icon:              "prometheus",
    configSchemaVersion: 1,
  },
  {
    provider:          "grafana_alerting",
    displayName:       "Grafana Alerting",
    category:          CATEGORIES.MONITORING,
    description:       "Receive Grafana unified alert notifications. Supports Grafana 8+ contact points.",
    capabilities:      ["receive_events", "normalize_events"],
    availabilityStatus: "available",
    documentationUrl:  "https://grafana.com/docs/grafana/latest/alerting/",
    icon:              "grafana",
    configSchemaVersion: 1,
  },

  // ── Beta ──────────────────────────────────────────────────────────────────
  {
    provider:          "opentelemetry",
    displayName:       "OpenTelemetry Collector",
    category:          CATEGORIES.TELEMETRY,
    description:       "Ingest traces, metrics, and logs from an OpenTelemetry Collector via OTLP/HTTP.",
    capabilities:      ["receive_events", "normalize_events"],
    availabilityStatus: "beta",
    documentationUrl:  "https://opentelemetry.io/docs/collector/",
    icon:              "opentelemetry",
    configSchemaVersion: 1,
  },
  {
    provider:          "datadog",
    displayName:       "Datadog",
    category:          CATEGORIES.MONITORING,
    description:       "Forward Datadog monitor alerts to AIRA for automated incident response.",
    capabilities:      ["receive_events", "normalize_events", "send_notifications"],
    availabilityStatus: "beta",
    documentationUrl:  "https://docs.datadoghq.com/integrations/webhooks/",
    icon:              "datadog",
    configSchemaVersion: 1,
  },

  // ── Coming soon ───────────────────────────────────────────────────────────
  {
    provider:          "newrelic",
    displayName:       "New Relic",
    category:          CATEGORIES.MONITORING,
    description:       "Ingest New Relic alerts and metrics for correlated incident detection.",
    capabilities:      ["receive_events", "normalize_events"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "newrelic",
    configSchemaVersion: 1,
  },
  {
    provider:          "sentry",
    displayName:       "Sentry",
    category:          CATEGORIES.MONITORING,
    description:       "Connect Sentry error alerts to AIRA incidents.",
    capabilities:      ["receive_events", "normalize_events"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "sentry",
    configSchemaVersion: 1,
  },
  {
    provider:          "elastic",
    displayName:       "Elastic Observability",
    category:          CATEGORIES.TELEMETRY,
    description:       "Bridge Elastic stack alerts into the AIRA incident pipeline.",
    capabilities:      ["receive_events", "normalize_events"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "elastic",
    configSchemaVersion: 1,
  },
  {
    provider:          "splunk",
    displayName:       "Splunk",
    category:          CATEGORIES.TELEMETRY,
    description:       "Ingest Splunk notable events and alerts.",
    capabilities:      ["receive_events"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "splunk",
    configSchemaVersion: 1,
  },
  {
    provider:          "aws_cloudwatch",
    displayName:       "AWS CloudWatch",
    category:          CATEGORIES.CLOUD,
    description:       "Route CloudWatch alarms and EventBridge rules to AIRA.",
    capabilities:      ["receive_events", "normalize_events"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "aws",
    configSchemaVersion: 1,
  },
  {
    provider:          "azure_monitor",
    displayName:       "Azure Monitor",
    category:          CATEGORIES.CLOUD,
    description:       "Forward Azure Monitor alerts and activity log events to AIRA.",
    capabilities:      ["receive_events", "normalize_events"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "azure",
    configSchemaVersion: 1,
  },
  {
    provider:          "gcp_monitoring",
    displayName:       "Google Cloud Monitoring",
    category:          CATEGORIES.CLOUD,
    description:       "Receive Google Cloud alerting policy notifications.",
    capabilities:      ["receive_events", "normalize_events"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "gcp",
    configSchemaVersion: 1,
  },
  {
    provider:          "kubernetes",
    displayName:       "Kubernetes",
    category:          CATEGORIES.INFRA,
    description:       "Connect a Kubernetes cluster for read-only health checks, resource discovery, and incident investigation.",
    capabilities: [
      "get_health",
      "receive_events",
      "normalize_events",
    ],
    availabilityStatus: "available",
    documentationUrl:  null,
    icon:              "kubernetes",
    configSchemaVersion: 1,
  },
  {
    provider:          "docker",
    displayName:       "Docker",
    category:          CATEGORIES.INFRA,
    description:       "Monitor Docker container lifecycle and health events.",
    capabilities:      ["receive_events", "get_health"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "docker",
    configSchemaVersion: 1,
  },
  {
    provider:          "pagerduty",
    displayName:       "PagerDuty",
    category:          CATEGORIES.INCIDENT,
    description:       "Bidirectional sync with PagerDuty incidents and on-call schedules.",
    capabilities:      ["receive_events", "send_notifications"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "pagerduty",
    configSchemaVersion: 1,
  },
  {
    provider:          "opsgenie",
    displayName:       "Opsgenie",
    category:          CATEGORIES.INCIDENT,
    description:       "Create and update Opsgenie alerts from AIRA incidents.",
    capabilities:      ["send_notifications"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "opsgenie",
    configSchemaVersion: 1,
  },
  {
    provider:          "servicenow",
    displayName:       "ServiceNow",
    category:          CATEGORIES.INCIDENT,
    description:       "Create ServiceNow incidents and change requests from AIRA.",
    capabilities:      ["send_notifications"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "servicenow",
    configSchemaVersion: 1,
  },
  {
    provider:          "slack",
    displayName:       "Slack",
    category:          CATEGORIES.COMMS,
    description:       "Send incident alerts and status updates to Slack channels.",
    capabilities:      ["send_notifications"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "slack",
    configSchemaVersion: 1,
  },
  {
    provider:          "msteams",
    displayName:       "Microsoft Teams",
    category:          CATEGORIES.COMMS,
    description:       "Post incident cards and updates to Microsoft Teams channels.",
    capabilities:      ["send_notifications"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "msteams",
    configSchemaVersion: 1,
  },
  {
    provider:          "email",
    displayName:       "Email",
    category:          CATEGORIES.COMMS,
    description:       "Send incident notifications and escalation alerts via SMTP.",
    capabilities:      ["send_notifications"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "email",
    configSchemaVersion: 1,
  },
  {
    provider:          "discord",
    displayName:       "Discord",
    category:          CATEGORIES.COMMS,
    description:       "Deliver incident alerts to Discord servers via webhook.",
    capabilities:      ["send_notifications"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "discord",
    configSchemaVersion: 1,
  },
  {
    provider:          "postgresql",
    displayName:       "PostgreSQL",
    category:          CATEGORIES.DATA,
    description:       "Monitor PostgreSQL health metrics and connection pool saturation.",
    capabilities:      ["get_health"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "postgresql",
    configSchemaVersion: 1,
  },
  {
    provider:          "mysql",
    displayName:       "MySQL",
    category:          CATEGORIES.DATA,
    description:       "Monitor MySQL replication lag and slow query signals.",
    capabilities:      ["get_health"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "mysql",
    configSchemaVersion: 1,
  },
  {
    provider:          "mongodb_integration",
    displayName:       "MongoDB",
    category:          CATEGORIES.DATA,
    description:       "Monitor Atlas or self-hosted MongoDB cluster health.",
    capabilities:      ["get_health"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "mongodb",
    configSchemaVersion: 1,
  },
  {
    provider:          "redis_integration",
    displayName:       "Redis",
    category:          CATEGORIES.DATA,
    description:       "Watch Redis memory usage and replication health.",
    capabilities:      ["get_health"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "redis",
    configSchemaVersion: 1,
  },
  {
    provider:          "rabbitmq",
    displayName:       "RabbitMQ",
    category:          CATEGORIES.DATA,
    description:       "Monitor RabbitMQ queue depth and consumer health.",
    capabilities:      ["get_health", "receive_events"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "rabbitmq",
    configSchemaVersion: 1,
  },
  {
    provider:          "kafka",
    displayName:       "Kafka",
    category:          CATEGORIES.DATA,
    description:       "Monitor Kafka consumer-group lag and broker availability.",
    capabilities:      ["get_health", "receive_events"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "kafka",
    configSchemaVersion: 1,
  },
  {
    provider:          "github_actions",
    displayName:       "GitHub Actions",
    category:          CATEGORIES.DEV,
    description:       "Receive deployment and workflow events from GitHub Actions.",
    capabilities:      ["receive_events", "normalize_events"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "github",
    configSchemaVersion: 1,
  },
  {
    provider:          "gitlab_ci",
    displayName:       "GitLab CI",
    category:          CATEGORIES.DEV,
    description:       "Ingest pipeline failure and deployment events from GitLab.",
    capabilities:      ["receive_events", "normalize_events"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "gitlab",
    configSchemaVersion: 1,
  },
  {
    provider:          "jenkins",
    displayName:       "Jenkins",
    category:          CATEGORIES.DEV,
    description:       "Bridge Jenkins build failures and deployment events into AIRA.",
    capabilities:      ["receive_events"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "jenkins",
    configSchemaVersion: 1,
  },
  {
    provider:          "argocd",
    displayName:       "Argo CD",
    category:          CATEGORIES.DEV,
    description:       "Receive Argo CD sync status and degraded application events.",
    capabilities:      ["receive_events", "normalize_events"],
    availabilityStatus: "coming_soon",
    documentationUrl:  null,
    icon:              "argocd",
    configSchemaVersion: 1,
  },
];

/** Providers whose connections can actually be created. */
const AVAILABLE_PROVIDERS = new Set(
  CATALOGUE.filter((d) => d.availabilityStatus === "available").map((d) => d.provider)
);

function findDefinition(provider) {
  return CATALOGUE.find((d) => d.provider === provider) ?? null;
}

module.exports = { CATALOGUE, CATEGORIES, AVAILABLE_PROVIDERS, findDefinition };
