#!/usr/bin/env node
/**
 * generate-secrets.js
 * Run: node k8s/generate-secrets.js
 * Creates k8s/secret-generated.yaml with base64-encoded values from .env
 * NEVER commit secret-generated.yaml to git.
 */

const fs = require('fs');
const path = require('path');

const envFile = path.join(__dirname, '..', '.env');
if (!fs.existsSync(envFile)) {
  console.error('ERROR: .env file not found at', envFile);
  process.exit(1);
}

const env = {};
fs.readFileSync(envFile, 'utf8').split('\n').forEach(line => {
  const match = line.match(/^([^#=]+)=(.*)$/);
  if (match) env[match[1].trim()] = match[2].trim().replace(/^["']|["']$/g, '');
});

function b64(val) {
  return Buffer.from(val || '').toString('base64');
}

// Always use in-cluster MongoDB service name for Kubernetes deployments
const mongoUri = `mongodb://admin:${env.MONGO_PASSWORD || 'password'}@aira-mongodb:27017/decision_engine?authSource=admin`;

const rabbitmqPass = env.RABBITMQ_PASS || env.RABBITMQ_PASSWORD || 'airapass';

const yaml = `# AUTO-GENERATED by generate-secrets.js — DO NOT COMMIT
apiVersion: v1
kind: Secret
metadata:
  name: aira-secrets
  namespace: aira
  labels:
    app: aira
type: Opaque
data:
  MONGODB_URI: ${b64(mongoUri)}
  AUDIT_SECRET: ${b64(env.AUDIT_SECRET || env.JWT_SECRET || 'change-me-32chars-minimum-secret')}
  SLACK_TOKEN: ${b64(env.SLACK_TOKEN || '')}
  OPENAI_API_KEY: ${b64(env.OPENAI_API_KEY || '')}
  mongodb-password: ${b64(env.MONGO_PASSWORD || 'password')}
  rabbitmq-password: ${b64(rabbitmqPass)}
`;

const outFile = path.join(__dirname, 'secret-generated.yaml');
fs.writeFileSync(outFile, yaml);
console.log('✅ Written:', outFile);
console.log('Apply with: kubectl apply -f k8s/secret-generated.yaml');
