"use strict";

const ENTITLEMENTS = Object.freeze({
  ORGANIZATIONS_MAX: "organizations.max",
  ENVIRONMENTS_MAX: "environments.max",
  MEMBERS_MAX: "members.max",
  TEAMS_MAX: "teams.max",
  PRODUCTION_ENVIRONMENT: "environments.production",
});

const PLAN_ENTITLEMENTS = Object.freeze({
  developer: {
    [ENTITLEMENTS.ORGANIZATIONS_MAX]: 1,
    [ENTITLEMENTS.ENVIRONMENTS_MAX]: 1,
    [ENTITLEMENTS.MEMBERS_MAX]: 1,
    [ENTITLEMENTS.TEAMS_MAX]: 1,
    [ENTITLEMENTS.PRODUCTION_ENVIRONMENT]: false,
  },

  team: {
    [ENTITLEMENTS.ORGANIZATIONS_MAX]: 1,
    [ENTITLEMENTS.ENVIRONMENTS_MAX]: 3,
    [ENTITLEMENTS.MEMBERS_MAX]: 10,
    [ENTITLEMENTS.TEAMS_MAX]: 5,
    [ENTITLEMENTS.PRODUCTION_ENVIRONMENT]: true,
  },

  business: {
    [ENTITLEMENTS.ORGANIZATIONS_MAX]: 1,
    [ENTITLEMENTS.ENVIRONMENTS_MAX]: 20,
    [ENTITLEMENTS.MEMBERS_MAX]: 100,
    [ENTITLEMENTS.TEAMS_MAX]: 50,
    [ENTITLEMENTS.PRODUCTION_ENVIRONMENT]: true,
  },

  enterprise: {
    [ENTITLEMENTS.ORGANIZATIONS_MAX]: null,
    [ENTITLEMENTS.ENVIRONMENTS_MAX]: null,
    [ENTITLEMENTS.MEMBERS_MAX]: null,
    [ENTITLEMENTS.TEAMS_MAX]: null,
    [ENTITLEMENTS.PRODUCTION_ENVIRONMENT]: true,
  },
});

module.exports = {
  ENTITLEMENTS,
  PLAN_ENTITLEMENTS,
};