"use strict";

const HUMAN_TASK_STATUS = Object.freeze({
  OPEN: "OPEN",
  ASSIGNED: "ASSIGNED",
  ACKNOWLEDGED: "ACKNOWLEDGED",
  IN_PROGRESS: "IN_PROGRESS",
  WAITING: "WAITING",
  RESOLVED: "RESOLVED",
  CANCELLED: "CANCELLED",
  EXPIRED: "EXPIRED",
});

const TAKEOVER_SESSION_STATUS = Object.freeze({
  REQUESTED: "REQUESTED",
  AUTHORIZED: "AUTHORIZED",
  ACTIVE: "ACTIVE",
  RELEASING: "RELEASING",
  RELEASED: "RELEASED",
  EXPIRED: "EXPIRED",
  REVOKED: "REVOKED",
  DENIED: "DENIED",
});

const CONTROL_LEASE_STATUS = Object.freeze({
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  RELEASED: "RELEASED",
  EXPIRED: "EXPIRED",
  REVOKED: "REVOKED",
});

const ASSIGNMENT_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  REASSIGNED: "REASSIGNED",
  RELEASED: "RELEASED",
  EXPIRED: "EXPIRED",
});

const ACKNOWLEDGEMENT_OUTCOME = Object.freeze({
  ACKNOWLEDGED: "ACKNOWLEDGED",
  DECLINED: "DECLINED",
  TIMED_OUT: "TIMED_OUT",
});

const HUMAN_TAKEOVER_INVARIANTS = Object.freeze({
  NEVER_AUTHORIZES_EXECUTION: true,
  EXACTLY_ONE_ACTIVE_LEASE_PER_INCIDENT: true,
  POSTGRES_IS_CONTROL_AUTHORITY: true,
  RETURN_REQUIRES_REEVALUATION: true,
  STALE_PLAN_RESUME_PROHIBITED: true,
});

module.exports = {
  HUMAN_TASK_STATUS,
  TAKEOVER_SESSION_STATUS,
  CONTROL_LEASE_STATUS,
  ASSIGNMENT_STATUS,
  ACKNOWLEDGEMENT_OUTCOME,
  HUMAN_TAKEOVER_INVARIANTS,
};