"use strict";


const {
  AUTONOMY_LEVEL,
} =
  require(
    "./recoveryCertification"
  );


const RUNTIME_AUTONOMY_POLICY_VERSION =
  "22.9-22.11-runtime-autonomy-v1";


const CERTIFICATE_STATUS =
  Object.freeze({
    CERTIFIED:
      "CERTIFIED",

    SUSPENDED:
      "SUSPENDED",

    REVOKED:
      "REVOKED",

    EXPIRED:
      "EXPIRED",

    FAILED:
      "FAILED",
  });


const AUTONOMY_RUNTIME_DECISION =
  Object.freeze({
    OBSERVE:
      "OBSERVE",

    DIAGNOSE:
      "DIAGNOSE",

    RECOMMEND:
      "RECOMMEND",

    REQUIRE_APPROVAL:
      "REQUIRE_APPROVAL",

    AUTONOMOUSLY_ELIGIBLE:
      "AUTONOMOUSLY_ELIGIBLE",

    BLOCKED:
      "BLOCKED",
  });


const AUTONOMY_RUNTIME_REASON =
  Object.freeze({
    CERTIFICATE_NOT_CERTIFIED:
      "CERTIFICATE_NOT_CERTIFIED",

    CERTIFICATE_SUSPENDED:
      "CERTIFICATE_SUSPENDED",

    CERTIFICATE_REVOKED:
      "CERTIFICATE_REVOKED",

    CERTIFICATE_EXPIRED:
      "CERTIFICATE_EXPIRED",

    CERTIFICATE_FAILED:
      "CERTIFICATE_FAILED",

    CERTIFICATE_CONSTRAINT_VIOLATION:
      "CERTIFICATE_CONSTRAINT_VIOLATION",

    TENANT_OBSERVE_ONLY:
      "TENANT_OBSERVE_ONLY",

    TENANT_RECOMMEND_ONLY:
      "TENANT_RECOMMEND_ONLY",

    TENANT_APPROVAL_REQUIRED:
      "TENANT_APPROVAL_REQUIRED",

    AUTONOMOUS_RECOVERY_DISABLED:
      "AUTONOMOUS_RECOVERY_DISABLED",

    PRODUCTION_AUTONOMY_DISABLED:
      "PRODUCTION_AUTONOMY_DISABLED",

    PRODUCTION_APPROVAL_REQUIRED:
      "PRODUCTION_APPROVAL_REQUIRED",

    DESTRUCTIVE_APPROVAL_REQUIRED:
      "DESTRUCTIVE_APPROVAL_REQUIRED",

    CONFIDENCE_BELOW_TENANT_MINIMUM:
      "CONFIDENCE_BELOW_TENANT_MINIMUM",

    ENVIRONMENT_CEILING:
      "ENVIRONMENT_CEILING",

    POLICY_REQUIRES_APPROVAL:
      "POLICY_REQUIRES_APPROVAL",

    POLICY_BLOCKED:
      "POLICY_BLOCKED",

    POLICY_UNKNOWN:
      "POLICY_UNKNOWN",

    RISK_MEDIUM:
      "RISK_MEDIUM",

    RISK_HIGH:
      "RISK_HIGH",

    RISK_CRITICAL:
      "RISK_CRITICAL",

    KILL_SWITCH_BLOCKED:
      "KILL_SWITCH_BLOCKED",

    KILL_SWITCH_UNKNOWN:
      "KILL_SWITCH_UNKNOWN",
  });


const REPUTATION_TREND =
  Object.freeze({
    NEW:
      "NEW",

    PROMOTING:
      "PROMOTING",

    STABLE:
      "STABLE",

    DEGRADING:
      "DEGRADING",

    SUSPENDED:
      "SUSPENDED",

    REVOKED:
      "REVOKED",
  });


const RECERTIFICATION_REASON =
  Object.freeze({
    NONE:
      "NONE",

    EXPIRING_SOON:
      "EXPIRING_SOON",

    EVIDENCE_STALE:
      "EVIDENCE_STALE",

    SAFETY_REGRESSION:
      "SAFETY_REGRESSION",

    LEVEL_DEMOTION:
      "LEVEL_DEMOTION",

    CERTIFICATE_SUSPENDED:
      "CERTIFICATE_SUSPENDED",

    CERTIFICATE_REVOKED:
      "CERTIFICATE_REVOKED",

    NEW_EVIDENCE_AVAILABLE:
      "NEW_EVIDENCE_AVAILABLE",
  });


const DEFAULT_RECERTIFICATION_POLICY =
  Object.freeze({
    expirationWarningDays:
      14,

    maximumEvidenceAgeDays:
      90,

    minimumNewEvidenceForReview:
      30,
  });


const POLICY_CEILING =
  Object.freeze({
    ELIGIBLE:
      AUTONOMY_LEVEL.L5,

    REQUIRES_APPROVAL:
      AUTONOMY_LEVEL.L3,

    BLOCKED:
      AUTONOMY_LEVEL.L0,

    UNKNOWN:
      AUTONOMY_LEVEL.L0,
  });


const RISK_CEILING =
  Object.freeze({
    LOW:
      AUTONOMY_LEVEL.L5,

    MEDIUM:
      AUTONOMY_LEVEL.L4,

    HIGH:
      AUTONOMY_LEVEL.L3,

    CRITICAL:
      AUTONOMY_LEVEL.L0,
  });


module.exports = {
  RUNTIME_AUTONOMY_POLICY_VERSION,

  CERTIFICATE_STATUS,

  AUTONOMY_RUNTIME_DECISION,

  AUTONOMY_RUNTIME_REASON,

  REPUTATION_TREND,

  RECERTIFICATION_REASON,

  DEFAULT_RECERTIFICATION_POLICY,

  POLICY_CEILING,

  RISK_CEILING,
};